name: attendance_app
description: Aplikasi absensi dan laporan pekerjaan harian berbasis Flutter dan Firebase
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^5.8.0
  cloud_firestore: ^4.19.0
  firebase_messaging: ^15.3.0
  geolocator: ^14.0.1
  provider: ^6.1.5
  open_file: ^4.4.0
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
